version: "3.9"
services:
    db:
        image: "postgres:13.2"
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql